version: "3.8"

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j_container
    restart: always
    environment:
      NEO4J_AUTH: <<neo4j-username>>/<<neo4j-password>>  # Username and password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  flask_app:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - neo4j
    ports:
      - "5001:5001"
    environment:
      - NEO4J_URI=bolt://neo4j_container:7687
      - NEO4J_USERNAME=<<neo4j-username>>
      - NEO4J_PASSWORD=<<neo4j-password>>
    command: ["python", "app.py"]

volumes:
  neo4j_data:


